### ISSUE TITLE
Bluetooth Advertisements, SecurityException: Permission Denial: startForeground

### ISSUE THREAD

**Issue by hlupico** [android/connectivity-samples#188]
Project: com.example.android.bluetoothadvertisements
On device: Google Pixel 2, Android OS 10

STR: 

- Launch app
- Wait for 5 second device sink to finis
- Toggle `Broadcast Device`
- App Crashes with Security Exception

Log cat:

`2020-04-19 13:30:34.436 26221-26221/com.example.android.bluetoothadvertisements E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.bluetoothadvertisements, PID: 26221
    java.lang.RuntimeException: Unable to create service com.example.android.bluetoothadvertisements.AdvertiserService: java.lang.SecurityException: Permission Denial: startForeground from pid=26221, uid=10010 requires android.permission.FOREGROUND_SERVICE
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3965)
        at android.app.ActivityThread.access$1500(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1875)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.SecurityException: Permission Denial: startForeground from pid=26221, uid=10010 requires android.permission.FOREGROUND_SERVICE
        at android.os.Parcel.createException(Parcel.java:2071)
        at android.os.Parcel.readException(Parcel.java:2039)
        at android.os.Parcel.readException(Parcel.java:1987)
        at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6136)
        at android.app.Service.startForeground(Service.java:707)
        at com.example.android.bluetoothadvertisements.AdvertiserService.goForeground(AdvertiserService.java:164)
        at com.example.android.bluetoothadvertisements.AdvertiserService.startAdvertising(AdvertiserService.java:133)
        at com.example.android.bluetoothadvertisements.AdvertiserService.onCreate(AdvertiserService.java:64)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3953)
        at android.app.ActivityThread.access$1500(ActivityThread.java:219) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1875) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ActivityManagerService.enforcePermission(ActivityManagerService.java:5928)
        at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:1259)
        at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:914)
        at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:13968)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2784)`

**Comment by camposmiguel** [comment]
Did you solve your problem? Try to include in the AndroidManifest.xml the next permission:

`<uses-permission android:name="android.permission.FOREGROUND_SERVICE"></uses-permission>`

I'va added this line, now the project is running but I can discover any device.

**Comment by mistyken** [comment]
I ran into this problem too. After I added the new permission I am getting this error when I tried to broadcast device
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.bluetoothadvertisements, PID: 7825
    android.app.RemoteServiceException: Bad notification for startForeground
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2038)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)`

**Comment by isaidamier** [comment]
Have you tried [this sample](https://github.com/android/connectivity-samples/tree/main/BluetoothAdvertisementsKotlin)?
