### ISSUE TITLE
Dtdi api is not available I try to use cross device sdk and shows Dtdi Api

### ISSUE THREAD

**Issue by Vedp1998** [android/connectivity-samples#281]
2022-10-17 20:02:18.557 11892-11938/com.google.crossdevice.sample.rps E/GoogleApiManager: Failed to get service from broker. 
    java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=com.google.crossdevice.sample.rps, sha256=[150dfc26248a7935505df583ef1ecb1d0cd4dbd4b2472e6096802b9d0529591e], atk=false, ver=223616044.true (go/gsrlt)
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2437)
        at android.os.Parcel.createException(Parcel.java:2421)
        at android.os.Parcel.readException(Parcel.java:2404)
        at android.os.Parcel.readException(Parcel.java:2346)
        at com.google.android.gms.common.internal.zzac.getService(com.google.android.gms:play-services-basement@@18.0.2:9)
        at com.google.android.gms.common.internal.BaseGmsClient.getRemoteService(com.google.android.gms:play-services-basement@@18.0.2:14)
        at com.google.android.gms.common.api.internal.zabt.run(com.google.android.gms:play-services-base@@18.0.1:7)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2022-10-17 20:02:18.558 11892-11892/com.google.crossdevice.sample.rps W/AnalyticsLogger: unable to determine logging consent
    java.util.concurrent.ExecutionException: failed to get logging availability
        at com.google.android.gms.dtdi.analytics.zzg.then(com.google.android.gms:play-services-dtdi@@16.0.0-beta01:4)
        at com.google.android.gms.tasks.zzc.run(com.google.android.gms:play-services-tasks@@18.0.1:3)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8663)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
     Caused by: com.google.android.gms.common.api.ApiException: 17: API: Dtdi.API is not available on this device. Connection failed with: ConnectionResult{statusCode=DEVELOPER_ERROR, resolution=null, message=null}
        at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@18.0.1:3)
        at com.google.android.gms.common.api.internal.ApiExceptionMapper.getException(com.google.android.gms:play-services-base@@18.0.1:1)
        at com.google.android.gms.common.api.internal.zag.zad(com.google.android.gms:play-services-base@@18.0.1:1)
        at com.google.android.gms.common.api.internal.zabq.zaE(com.google.android.gms:play-services-base@@18.0.1:7)
        at com.google.android.gms.common.api.internal.zabq.zaD(com.google.android.gms:play-services-base@@18.0.1:2)
        at com.google.android.gms.common.api.internal.zabq.zar(com.google.android.gms:play-services-base@@18.0.1:24)
        at com.google.android.gms.common.api.internal.zabt.run(com.google.android.gms:play-services-base@@18.0.1:11)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2022-10-17 20:02:18.559 11892-11892/com.google.crossdevice.sample.rps E/SessionsTPGameManager: Failed to launch opponent picker
    com.google.android.gms.common.api.ApiException: 17: API: Dtdi.API is not available on this device. Connection failed with: ConnectionResult{statusCode=DEVELOPER_ERROR, resolution=null, message=null}
        at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@18.0.1:3)
        at com.google.android.gms.common.api.internal.ApiExceptionMapper.getException(com.google.android.gms:play-services-base@@18.0.1:1)
        at com.google.android.gms.common.api.internal.zag.zad(com.google.android.gms:play-services-base@@18.0.1:1)
        at com.google.android.gms.common.api.internal.zabq.zaE(com.google.android.gms:play-services-base@@18.0.1:7)
        at com.google.android.gms.common.api.internal.zabq.zaD(com.google.android.gms:play-services-base@@18.0.1:2)
        at com.google.android.gms.common.api.internal.zabq.zar(com.google.android.gms:play-services-base@@18.0.1:24)
        at com.google.android.gms.common.api.internal.zabt.run(com.google.android.gms:play-services-base@@18.0.1:11)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by yeunbok2g** [comment]
I have the same issue. And I joined beta program. (when i checked on my phone app, Google play service(beta) is installed succesfully). But It didn't work when I select TWO_PLAYERS(DISCOVERY API).

**Failed to get service from broker.** 
**java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=com.google.crossdevice.sample.rps,** sha256=[16188b0968a05a5b9d67241455874c187340663a3b1f18d9fe916c7fb872a423], atk=false, ver=224212044.true (go/gsrlt)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2426)
	at android.os.Parcel.createException(Parcel.java:2410)
	at android.os.Parcel.readException(Parcel.java:2393)
	at android.os.Parcel.readException(Parcel.java:2335)
	at com.google.android.gms.common.internal.zzac.getService(com.google.android.gms:play-services-basement@@18.0.2:9)
	at com.google.android.gms.common.internal.BaseGmsClient.getRemoteService(com.google.android.gms:play-services-basement@@18.0.2:14)
	at com.google.android.gms.common.api.internal.zabt.run(com.google.android.gms:play-services-base@@18.0.1:7)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by mauricelam** [comment]
Sorry for the delayed response. You are right that the error message indicates that you need to enroll in the beta program. Additionally, after enrolling and Google Play Services successfully updated, you will need to restart your device in order for it to take effect.

We have also made a change recently so that the reboot is no longer necessary, and that change will be rolling out in the coming weeks.
